### Cross Validation

In [ ]:
we basically divide data (like 100 samples into 5 different 20 samples each, then take 1st '20 sample' for testing and 
remaining 4 (80 samples for training), Similarly change test sample 1 to 5 then test and take average of test data , 
and cross validate that data.
                          
K-fold , cross_val_score - used the same condition.
                          
It is better than train_test_split method.
It also helps to choose which algorithm to work with after checking its accuracy of mean.

#### Import libraries

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits                    # using digits dataset of sklearn

In [2]:
digits = load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [4]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [5]:
len(x_test)

540

### Logistic Regression model

In [6]:
lr = LogisticRegression()   
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9518518518518518

### SVM model

In [7]:
svm = SVC(gamma='scale')                   # trying SVM
svm.fit(x_train,y_train) 
svm.score(x_test,y_test)

0.9888888888888889

### Random forest Classifier

In [8]:
rf = RandomForestClassifier(n_estimators=40)        # trying Random Forest
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

## ----------------------------------

## K fold

In [9]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)        # creating no. of K folds = 3 
kf 

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):        # kf=3 folds , so it divide these into 3 train-test data 
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
def get_score(model,x_train,x_test,y_train,y_test):          # defining get_score()
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [12]:
get_score(LogisticRegression(), x_train,x_test,y_train,y_test)    # we can use this fun. and pass different like: SVC() or other

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9518518518518518

## ------------------------------------------

## Stratified K Fold

StratifiedKFold -- similar to Kfold, when you are separating out your folds it will divide each of classification categories
                  in a uniform way.

In [13]:
from sklearn.model_selection import StratifiedKFold
 
folds = StratifiedKFold(n_splits=3)     # same as KFold

In [14]:
# we can use : cross_val_score() method instead of thi so long code or method


scores_l = []          # for logistic Regression
scores_svm = []         # SVM
scores_rf = []           # random forest

for train_index, test_index in kf.split(digits.data):                          # same as above , but now using digits.data 
    x_train,x_test,y_train,y_test = digits.data[train_index], digits.data[test_index], \
                                    digits.target[train_index], digits.target[test_index]  
    scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='auto'), x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(gamma='scale'), x_train,x_test,y_train,y_test))    
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train,x_test,y_train,y_test))    

In [15]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [16]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [17]:
scores_rf

[0.9232053422370617, 0.9482470784641068, 0.9181969949916527]

## -------------------------------------------------

## cross_val_score

In [18]:
from sklearn.model_selection import cross_val_score             # cross_val_score() method


In [22]:
cr1 = cross_val_score(LogisticRegression(solver='liblinear',multi_class='auto'), digits.data, digits.target,cv=3)
print(cr1)
print('Mean score : ', cr1.mean())

[0.89534884 0.94991653 0.90939597]
Mean score :  0.9182204459698582


In [23]:
cr2 = cross_val_score(SVC(gamma='scale'), digits.data, digits.target,cv=3)
print(cr2)
print('Mean score : ', cr2.mean())

[0.96677741 0.97996661 0.9647651 ]
Mean score :  0.9705030401091262


In [24]:
cr3 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target,cv=3)
print(cr3)
print('Mean score : ', cr3.mean())

[0.92192691 0.94824708 0.92114094]
Mean score :  0.9304383094534753
