#  Save  and load trained model using
    1. Pickle
    2. sklearn joblib

##### training a model using a Dataset, dump that model into a file, and load that file into an var.(like model) then ask a question trained model and use for prediction.

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [4]:
model.coef_                          # y=mx+c         , m-coeff.(slope)

array([135.78767123])

In [5]:
model.intercept_                    # c-intercept

180616.43835616432

In [7]:
model.predict([[5000]])

array([859554.79452055])

## Pickle

In [8]:
import pickle

In [9]:
with open('model_pickle','wb') as f:        # writing (or creating) a file in binary format  -> 'model_pickle'  is file name
    pickle.dump(model,f)                    # dump the (model) file in binary

In [10]:
with open('model_pickle','rb') as f:                # now read that file  as  f  
    mp = pickle.load(f)                            # and load the f file into  object -> mp

In [12]:
# Now we can use this object -> mp   as to predict

mp.predict([[5000]])

array([859554.79452055])

## ----------------------------------------

## Joblib

In [14]:
from sklearn.externals import joblib

In [15]:
joblib.dump(model,'model_joblib')        #(1.model name , 2.file name )    dump and save that model into the file

['model_joblib']

In [16]:
mj = joblib.load('model_joblib')        # load file into an object - mj (or give any name)

In [17]:
mj.predict([[5000]])                # then use for prediction

array([859554.79452055])

In [18]:
mj.coef_

array([135.78767123])

In [19]:
mj.intercept_

180616.43835616432